# Generated by Django 5.0.2 on 2024-07-13 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VentasPesqueras',
            fields=[
                ('fechaVenta', models.DateField()),
                ('provincia', models.CharField(max_length=50)),
                ('lonja', models.CharField(max_length=100)),
                ('tipoEspecie', models.CharField(max_length=20)),
                ('faoEspecie', models.CharField(max_length=3)),
                ('nombreEspecie', models.CharField(max_length=100)),
                ('totalKilos', models.DecimalField(decimal_places=2, max_digits=15)),
                ('totalEuros', models.DecimalField(decimal_places=2, max_digits=15)),
                ('idVenta', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
